### PR TITLE
Add ClumpSource creation methods to Clump object

### PR DESCRIPTION
**Pull request by williamboxhall**
As discussed in https://github.com/fwbrasil/clump/pull/35, I think it make things nice and simple to have one single entry point for using Clump.

I don't think the interface is too polluted like this

@fwbrasil let's discuss

### CODE REVIEW

**Comment by fwbrasil** [comment]
Remember to move the source creation tests back to the ```ClumpApiSpec```. LGTM

**Comment by williamboxhall** [comment]
Fixed the merge/compilation issues

**Comment by williamboxhall** [comment]
> Remember to move the source creation tests back to the ClumpApiSpec. LGTM

okay

**Comment by williamboxhall** [comment]
Actually @fwbrasil even though we're technically going through the Clump convenience methods, I think these tests makes sense to stay here because this is the class they are about

**Comment by fwbrasil** [comment]
We need at least coverage to the ```Clump``` object methods.

**Comment by fwbrasil** [comment]
Okay, there is coverage. :)

**Pull request merged**
